name: CI Reports

on:
  push:
  pull_request:

jobs:
  ci-reports:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn -B clean test
      
    - name: Generate reports
      run: mvn -B jacoco:report pmd:pmd pmd:check
      
    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf
        
    - name: Make script executable
      run: chmod +x scripts/html_to_png.sh
      
    - name: Convert HTML reports to PNG
      run: bash scripts/html_to_png.sh
      
    - name: Upload CI reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ci-reports
        path: reports/*