name: main Branch

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 4
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Maven Package
        run: mvn -B -f IndividualProject/pom.xml clean package -DskipTests
      - name: Maven Verify
        run: mvn -B -f IndividualProject/pom.xml clean verify -Pintegration-test